// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.8
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Exec02.FrontEnd.Infra.Data.EFModels
{

    // News
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.5.0")]
    public class NewsConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<News>
    {
        public NewsConfiguration()
            : this("dbo")
        {
        }

        public NewsConfiguration(string schema)
        {
            ToTable("News", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.Title).HasColumnName(@"Title").HasColumnType("nvarchar").IsRequired().HasMaxLength(100);
            Property(x => x.Content).HasColumnName(@"Content").HasColumnType("nvarchar(max)").IsRequired();
            Property(x => x.PublishTime).HasColumnName(@"PublishTime").HasColumnType("datetime").IsRequired();
            Property(x => x.CreatedTime).HasColumnName(@"CreatedTime").HasColumnType("datetime").IsRequired();
            Property(x => x.LastModifiedTime).HasColumnName(@"LastModifiedTime").HasColumnType("datetime").IsRequired();
        }
    }

}
// </auto-generated>
