// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.8
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Exec02.FrontEnd.Infra.Data.EFModels
{

    // News
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.5.0")]
    public class News
    {
        public int Id { get; set; } // Id (Primary key)
        public string Title { get; set; } // Title (length: 100)
        public string Content { get; set; } // Content
        public System.DateTime PublishTime { get; set; } // PublishTime
        public System.DateTime CreatedTime { get; set; } // CreatedTime
        public System.DateTime LastModifiedTime { get; set; } // LastModifiedTime

        public News()
        {
            CreatedTime = System.DateTime.Now;
            LastModifiedTime = System.DateTime.Now;
        }
    }

}
// </auto-generated>
